// Plain CommonJS copy of the 66-book canon (structural data only: names,
// USFM ids, chapter counts) so this standalone Node script doesn't need a
// TypeScript build step to import expo-app/src/data.ts. Keep in sync with
// that file if the canon list ever changes (it won't — this is fixed).
const ALL_BIBLE_BOOKS = [
  { id: 'GEN', name: 'Genesis', testament: 'ot', chapters: 50 },
  { id: 'EXO', name: 'Exodus', testament: 'ot', chapters: 40 },
  { id: 'LEV', name: 'Leviticus', testament: 'ot', chapters: 27 },
  { id: 'NUM', name: 'Numbers', testament: 'ot', chapters: 36 },
  { id: 'DEU', name: 'Deuteronomy', testament: 'ot', chapters: 34 },
  { id: 'JOS', name: 'Joshua', testament: 'ot', chapters: 24 },
  { id: 'JDG', name: 'Judges', testament: 'ot', chapters: 21 },
  { id: 'RUT', name: 'Ruth', testament: 'ot', chapters: 4 },
  { id: '1SA', name: '1 Samuel', testament: 'ot', chapters: 31 },
  { id: '2SA', name: '2 Samuel', testament: 'ot', chapters: 24 },
  { id: '1KI', name: '1 Kings', testament: 'ot', chapters: 22 },
  { id: '2KI', name: '2 Kings', testament: 'ot', chapters: 25 },
  { id: '1CH', name: '1 Chronicles', testament: 'ot', chapters: 29 },
  { id: '2CH', name: '2 Chronicles', testament: 'ot', chapters: 36 },
  { id: 'EZR', name: 'Ezra', testament: 'ot', chapters: 10 },
  { id: 'NEH', name: 'Nehemiah', testament: 'ot', chapters: 13 },
  { id: 'EST', name: 'Esther', testament: 'ot', chapters: 10 },
  { id: 'JOB', name: 'Job', testament: 'ot', chapters: 42 },
  { id: 'PSA', name: 'Psalms', testament: 'ot', chapters: 150 },
  { id: 'PRO', name: 'Proverbs', testament: 'ot', chapters: 31 },
  { id: 'ECC', name: 'Ecclesiastes', testament: 'ot', chapters: 12 },
  { id: 'SNG', name: 'Song of Solomon', testament: 'ot', chapters: 8 },
  { id: 'ISA', name: 'Isaiah', testament: 'ot', chapters: 66 },
  { id: 'JER', name: 'Jeremiah', testament: 'ot', chapters: 52 },
  { id: 'LAM', name: 'Lamentations', testament: 'ot', chapters: 5 },
  { id: 'EZK', name: 'Ezekiel', testament: 'ot', chapters: 48 },
  { id: 'DAN', name: 'Daniel', testament: 'ot', chapters: 12 },
  { id: 'HOS', name: 'Hosea', testament: 'ot', chapters: 14 },
  { id: 'JOL', name: 'Joel', testament: 'ot', chapters: 3 },
  { id: 'AMO', name: 'Amos', testament: 'ot', chapters: 9 },
  { id: 'OBA', name: 'Obadiah', testament: 'ot', chapters: 1 },
  { id: 'JON', name: 'Jonah', testament: 'ot', chapters: 4 },
  { id: 'MIC', name: 'Micah', testament: 'ot', chapters: 7 },
  { id: 'NAM', name: 'Nahum', testament: 'ot', chapters: 3 },
  { id: 'HAB', name: 'Habakkuk', testament: 'ot', chapters: 3 },
  { id: 'ZEP', name: 'Zephaniah', testament: 'ot', chapters: 3 },
  { id: 'HAG', name: 'Haggai', testament: 'ot', chapters: 2 },
  { id: 'ZEC', name: 'Zechariah', testament: 'ot', chapters: 14 },
  { id: 'MAL', name: 'Malachi', testament: 'ot', chapters: 4 },
  { id: 'MAT', name: 'Matthew', testament: 'nt', chapters: 28 },
  { id: 'MRK', name: 'Mark', testament: 'nt', chapters: 16 },
  { id: 'LUK', name: 'Luke', testament: 'nt', chapters: 24 },
  { id: 'JHN', name: 'John', testament: 'nt', chapters: 21 },
  { id: 'ACT', name: 'Acts', testament: 'nt', chapters: 28 },
  { id: 'ROM', name: 'Romans', testament: 'nt', chapters: 16 },
  { id: '1CO', name: '1 Corinthians', testament: 'nt', chapters: 16 },
  { id: '2CO', name: '2 Corinthians', testament: 'nt', chapters: 13 },
  { id: 'GAL', name: 'Galatians', testament: 'nt', chapters: 6 },
  { id: 'EPH', name: 'Ephesians', testament: 'nt', chapters: 6 },
  { id: 'PHP', name: 'Philippians', testament: 'nt', chapters: 4 },
  { id: 'COL', name: 'Colossians', testament: 'nt', chapters: 4 },
  { id: '1TH', name: '1 Thessalonians', testament: 'nt', chapters: 5 },
  { id: '2TH', name: '2 Thessalonians', testament: 'nt', chapters: 3 },
  { id: '1TI', name: '1 Timothy', testament: 'nt', chapters: 6 },
  { id: '2TI', name: '2 Timothy', testament: 'nt', chapters: 4 },
  { id: 'TIT', name: 'Titus', testament: 'nt', chapters: 3 },
  { id: 'PHM', name: 'Philemon', testament: 'nt', chapters: 1 },
  { id: 'HEB', name: 'Hebrews', testament: 'nt', chapters: 13 },
  { id: 'JAS', name: 'James', testament: 'nt', chapters: 5 },
  { id: '1PE', name: '1 Peter', testament: 'nt', chapters: 5 },
  { id: '2PE', name: '2 Peter', testament: 'nt', chapters: 3 },
  { id: '1JN', name: '1 John', testament: 'nt', chapters: 5 },
  { id: '2JN', name: '2 John', testament: 'nt', chapters: 1 },
  { id: '3JN', name: '3 John', testament: 'nt', chapters: 1 },
  { id: 'JUD', name: 'Jude', testament: 'nt', chapters: 1 },
  { id: 'REV', name: 'Revelation', testament: 'nt', chapters: 22 },
];

module.exports = { ALL_BIBLE_BOOKS };
